### ISSUE TITLE
Questions about the Lifecycle of Gaussians.

### ISSUE THREAD

**Issue by tb2-sy** [BoMingZhao/GaussianPrediction#3]
Thanks for your nice work!
I have some questions about implentment details. Is delta opacity added to the opacity of the gaussian in canonical space, so that the opacity is also deformable? If so, is the lifecycle multiplied by the opacity after deformation?
![141294bc0d47f000574ecd0075b9ecf0](https://github.com/BoMingZhao/GaussianPrediction/assets/61854446/9bef7cdf-3a80-4887-9ef3-46f9d28912bd)

**Comment by BoMingZhao** [comment]
> I have some questions about implentment details. Is delta opacity added to the opacity of the gaussian in canonical space, so that the opacity is also deformable? If so, is the lifecycle multiplied by the opacity after deformation?

Hi! Thanks for your interest in our work.
Our lifecycle multiplies the original Gaussian's opacity attribute when you need to render, and the opacity attribute **does not** add with delta. This means that the deformability of the Gaussian's opacity in the canonical space is achieved by multiplying it by different lifecycles at different times.

**Comment by tb2-sy** [comment]
> > I have some questions about implentment details. Is delta opacity added to the opacity of the gaussian in canonical space, so that the opacity is also deformable? If so, is the lifecycle multiplied by the opacity after deformation?
> 
> Hi! Thanks for your interest in our work. Our lifecycle multiplies the original Gaussian's opacity attribute when you need to render, and the opacity attribute **does not** add with delta. This means that the deformability of the Gaussian's opacity in the canonical space is achieved by multiplying it by different lifecycles at different times.

Thanks, I understand.
