### ISSUE TITLE
Questions about the annealing noise.

### ISSUE THREAD

**Issue by tb2-sy** [BoMingZhao/GaussianPrediction#4]
Thanks for your nice work!
My question is, is the annealing noise added to the position before it is input into the deformable mlp?

**Comment by tb2-sy** [comment]
Sorry to bother you again, I am trying to reproduce your method, could you please tell me the dimension of the motion feature?

**Comment by BoMingZhao** [comment]
> deformable mlp

Hi!
Yes, we first add annealing noise and then pass it through a deformable MLP. The dimension of the motion feature we use is 32. The deformable MLP is a four-layer MLP with 256 units.

**Comment by BoMingZhao** [comment]
Closed due to inactivity. Please feel free to reopen if you have any questions.
