### ISSUE TITLE
Training failure due to the scale difference between the offset and the canonical space gs.

### ISSUE THREAD

**Issue by Time-Lord12th** [BoMingZhao/GaussianPrediction#5]
Hello，
Thanks for your great work. Have you ever encountered training failure due to the scale difference between the offset and the canonical space gs? 
For example, the position range of the canonical space gs is [-0.2, 0.2], while the offset range output by the deformation model is [-1, 1]. So most of the gs will be deformed out of the camera's field of view, causing a large difference between the rendered image and the ground truth, making it impossible for the model to optimize properly.
Do you have any opinion on this issue?

**Comment by BoMingZhao** [comment]
Hi,
I haven't encountered this problem before. I did not make any additional constraints on the deformable MLP
So it may be related to the initialization of the motion feature. Here is my code for initializing the motion feature:

```
self.motion_feature = nn.Parameter(1e-3 * (2 * torch.rand((self.N_pcd_init, self.motion_feature_dim)).cuda() - 1))
```
I hope this helps you!

**Comment by Time-Lord12th** [comment]
Thanks, I will check some initialization.
